insert into familia (nombre) values('	Anacardiaceae	')
insert into familia (nombre) values('	Annonaceae	')
insert into familia (nombre) values('	Apocynaceae	')
insert into familia (nombre) values('	Arecaceae	')
insert into familia (nombre) values('	Boraginaceae	')
insert into familia (nombre) values('	Cannabaceae	')
insert into familia (nombre) values('	Capparaceae	')
insert into familia (nombre) values('	Cecropiaceae	')
insert into familia (nombre) values('	Celastraceae	')
insert into familia (nombre) values('	Chrysobalanaceae	')
insert into familia (nombre) values('	Combretaceae	')
insert into familia (nombre) values('	Elaeocarpaceae	')
insert into familia (nombre) values('	Euphorbiaceae	')
insert into familia (nombre) values('	Fabaceae	')
insert into familia (nombre) values('	Lauraceae	')
insert into familia (nombre) values('	Loganiaceae	')
insert into familia (nombre) values('	Malvaceae	')
insert into familia (nombre) values('	Meliacae	')
insert into familia (nombre) values('	Meliaceae	')
insert into familia (nombre) values('	Moraceae	')
insert into familia (nombre) values('	Myrtaceae	')
insert into familia (nombre) values('	Nyctaginaceae	')
insert into familia (nombre) values('	Ochnaceae	')
insert into familia (nombre) values('	Phyllantaceae	')
insert into familia (nombre) values('	Phyllanthaceae	')
insert into familia (nombre) values('	Picramniaceae	')
insert into familia (nombre) values('	Poaceae	')
insert into familia (nombre) values('	Polygonaceae	')
insert into familia (nombre) values('	Rhamnaceae	')
insert into familia (nombre) values('	Rubiaceae	')
insert into familia (nombre) values('	Rutaceae	')
insert into familia (nombre) values('	Salicaceae	')
insert into familia (nombre) values('	Sapindaceae	')
insert into familia (nombre) values('	Sapotaceae	')
insert into familia (nombre) values('	Simaroubaceae	')
insert into familia (nombre) values('	Solanaceae	')
insert into familia (nombre) values('	Urticaceae	')

insert into especie (nombreCientifico,idFamilia) values('	Albizia inundata (Mart.) Barneby & J.W. Grimes	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Alibertia sp.	 ',	30	)
insert into especie (nombreCientifico,idFamilia) values('	Allophylus floribundus (Poepp.) Radlk.	 ',	33	)
insert into especie (nombreCientifico,idFamilia) values('	Allophylus sp.	 ',	33	)
insert into especie (nombreCientifico,idFamilia) values('	Amaioua intermedia Mart et Schult ex Schult f.	 ',	30	)
insert into especie (nombreCientifico,idFamilia) values('	Andira inermis (Wright) DC.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Aniba sp.	 ',	15	)
insert into especie (nombreCientifico,idFamilia) values('	Aniba aff muca (Ruiz & Pav.) Mez	 ',	15	)
insert into especie (nombreCientifico,idFamilia) values('	Annona hypoglauca Mart. 	 ',	2	)
insert into especie (nombreCientifico,idFamilia) values('	Annona sp.	 ',		)
insert into especie (nombreCientifico,idFamilia) values('	Apeiba aspera Aubl.	 ',	17	)
insert into especie (nombreCientifico,idFamilia) values('	Apeiba sp.	 ',	17	)
insert into especie (nombreCientifico,idFamilia) values('	Bactris sp.	 ',	4	)
insert into especie (nombreCientifico,idFamilia) values('	Banara arguta Briq.	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Banara sp.	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Buchenavia parvifolia Ducke	 ',	11	)
insert into especie (nombreCientifico,idFamilia) values('	Buchenavia sp.	 ',	11	)
insert into especie (nombreCientifico,idFamilia) values('	Calliandra surinamensis Benth.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Casearia aff aculeata Jacq.	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Casearia mariquitensis Kunth	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Casearia sp.	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Casearia sylvestris Sw.	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Cecropia  sp.	 ',	8	)
insert into especie (nombreCientifico,idFamilia) values('	Cedrela odorata L.	 ',	19	)
insert into especie (nombreCientifico,idFamilia) values('	Celtis sp.	 ',	6	)
insert into especie (nombreCientifico,idFamilia) values('	Cestrum sp.	 ',	36	)
insert into especie (nombreCientifico,idFamilia) values('	Chaetocarpus sp.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Chrysophyllum venezuelanense (Pierre) T.D. Penn.	 ',	34	)
insert into especie (nombreCientifico,idFamilia) values('	Clitoria arborea Benth.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Coccoloba densifrons Mart. ex Meisn.	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Coccoloba sp.	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Coccoloba peruviana Lindau	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Conceveiba guianensis Aubl.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Conceveiba sp.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Cordia collococca L.	 ',	5	)
insert into especie (nombreCientifico,idFamilia) values('	Crateva tapia L.	 ',	7	)
insert into especie (nombreCientifico,idFamilia) values('	Croton schiedeanus Schltdl.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Croton tessmannii Mansf.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Cupania cinerea Poepp.	 ',	33	)
insert into especie (nombreCientifico,idFamilia) values('	Cynometra bauhiniifolia Benth.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Duguetia sp.	 ',	2	)
insert into especie (nombreCientifico,idFamilia) values('	Endlicheria paniculata (Sprengel) J.F. Macbride	 ',	15	)
insert into especie (nombreCientifico,idFamilia) values('	Eugenia sp.	 ',	21	)
insert into especie (nombreCientifico,idFamilia) values('	Ficus insipida Willd.	 ',	20	)
insert into especie (nombreCientifico,idFamilia) values('	Gavarretia sp.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Genipa americana L.	 ',	30	)
insert into especie (nombreCientifico,idFamilia) values('	Guadua sp.	 ',	27	)
insert into especie (nombreCientifico,idFamilia) values('	Guatteria sp.	 ',	2	)
insert into especie (nombreCientifico,idFamilia) values('	Guazuma crinita Mart.	 ',	17	)
insert into especie (nombreCientifico,idFamilia) values('	Guazuma ulmifolia Lam.	 ',	17	)
insert into especie (nombreCientifico,idFamilia) values('	Hirtella gracilipes (Hook. f.) Prance	 ',	10	)
insert into especie (nombreCientifico,idFamilia) values('	Hirtella sp.	 ',	10	)
insert into especie (nombreCientifico,idFamilia) values('	Hura crepitans L.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Inga sp.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Inga acicularis T.D.Penn.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Laetia corymbulosa Spruce ex Benth. 	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Licania sp.	 ',	10	)
insert into especie (nombreCientifico,idFamilia) values('	Licania octandra (Hoffmanns. ex Schult.) Kuntze	 ',	10	)
insert into especie (nombreCientifico,idFamilia) values('	Licaria sp.	 ',	15	)
insert into especie (nombreCientifico,idFamilia) values('	Luehea sp.	 ',	17	)
insert into especie (nombreCientifico,idFamilia) values('	Lunania parviflora Spruce ex Benth	 ',	32	)
insert into especie (nombreCientifico,idFamilia) values('	Mabea sp.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Machaerium sp.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Maclura tinctoria (L.) D. Don ex Steud.	 ',	20	)
insert into especie (nombreCientifico,idFamilia) values('	Manilkara sp.	 ',	34	)
insert into especie (nombreCientifico,idFamilia) values('	Margaritaria nobilis L.f	 ',	25	)
insert into especie (nombreCientifico,idFamilia) values('	Matayba macrostylis Radlk. 	 ',	33	)
insert into especie (nombreCientifico,idFamilia) values('	Matayba sp.	 ',	33	)
insert into especie (nombreCientifico,idFamilia) values('	Maytenus macrocarpa (Ruiz & Pav.) Briq.	 ',	9	)
insert into especie (nombreCientifico,idFamilia) values('	Mosannona sp.	 ',	2	)
insert into especie (nombreCientifico,idFamilia) values('	Myrcia sp.	 ',	21	)
insert into especie (nombreCientifico,idFamilia) values('	Neea parviflora Poepp. & Endl. Cf.	 ',	22	)
insert into especie (nombreCientifico,idFamilia) values('	Neea divaricata Poepp. & Endl.	 ',	22	)
insert into especie (nombreCientifico,idFamilia) values('	Ocotea sp.	 ',	15	)
insert into especie (nombreCientifico,idFamilia) values('	Ouratea aromatica J.F. Macbr.	 ',	23	)
insert into especie (nombreCientifico,idFamilia) values('	Ouratea iquitosensis J.F. Macbr.	 ',	23	)
insert into especie (nombreCientifico,idFamilia) values('	Palicourea sp.	 ',	30	)
insert into especie (nombreCientifico,idFamilia) values('	Pausandra martini Baill. 	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Phyllanthus attenuatus Miq.	 ',	24	)
insert into especie (nombreCientifico,idFamilia) values('	Phyllantus sp.	 ',	24	)
insert into especie (nombreCientifico,idFamilia) values('	Picramniaaff. latifolia Tul.	 ',	26	)
insert into especie (nombreCientifico,idFamilia) values('	Pourouma sp.	 ',	37	)
insert into especie (nombreCientifico,idFamilia) values('	Pouteria caimito (Ruiz & Pav.) Radlk.	 ',	34	)
insert into especie (nombreCientifico,idFamilia) values('	Pouteria glomerata (Miq.) Radlk.	 ',	34	)
insert into especie (nombreCientifico,idFamilia) values('	Pseudobombax septenatum (Jacq.) Dugand	 ',	17	)
insert into especie (nombreCientifico,idFamilia) values('	Psidium sp.	 ',	21	)
insert into especie (nombreCientifico,idFamilia) values('	Pterocarpus amazonum (Mart. ex Benth.) Amshoff	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Pterocarpus rohrii Vahl	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Rhamnidium elaeocarpum Reissek	 ',	29	)
insert into especie (nombreCientifico,idFamilia) values('	Rhamnus jelskii Szyszy‚.	 ',	29	)
insert into especie (nombreCientifico,idFamilia) values('	Rhamnus sp.	 ',	29	)
insert into especie (nombreCientifico,idFamilia) values('	Sagotia racemosa Baill.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Salacia aff. macrantha A.C. Sm.	 ',	9	)
insert into especie (nombreCientifico,idFamilia) values('	Sapium glandulosum (L.) Morong	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Sapium sp.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Senefeldera sp.	 ',	13	)
insert into especie (nombreCientifico,idFamilia) values('	Simaba orinocensis Kunth	 ',	35	)
insert into especie (nombreCientifico,idFamilia) values('	Sloanea guianensis (Aubl.) Benth.	 ',	12	)
insert into especie (nombreCientifico,idFamilia) values('	Sorocea hirtella Mildbraed	 ',	20	)
insert into especie (nombreCientifico,idFamilia) values('	Spondias mombin L.	 ',	1	)
insert into especie (nombreCientifico,idFamilia) values('	Strychnos sp.	 ',	16	)
insert into especie (nombreCientifico,idFamilia) values('	Swartzia sp.	 ',	14	)
insert into especie (nombreCientifico,idFamilia) values('	Symmeria paniculata Benth. 	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Tabernaemontana sp.	 ',	3	)
insert into especie (nombreCientifico,idFamilia) values('	Talisia sp.	 ',	33	)
insert into especie (nombreCientifico,idFamilia) values('	Terminalia amazonia (J.F. Gmel.) Exell	 ',	11	)
insert into especie (nombreCientifico,idFamilia) values('	Theobroma sp.	 ',	17	)
insert into especie (nombreCientifico,idFamilia) values('	Trichilia sp.	 ',	18	)
insert into especie (nombreCientifico,idFamilia) values('	Trichilia singularis C.DC.	 ',	18	)
insert into especie (nombreCientifico,idFamilia) values('	Triplaris peruviana Fisch. & Meyer ex C.A. Meyer	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Triplaris sp.	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Triplaris peruviana Fisch. & Meyer ex C.A. Meyer	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Triplaris surinamensis Cham.	 ',	28	)
insert into especie (nombreCientifico,idFamilia) values('	Zanthoxylum compactum (Huber ex Albuq.) P.G.Waterman 	 ',	31	)
insert into especie (nombreCientifico,idFamilia) values('	Zygia sp.	 ',	14	)

